exports.catchErr = ctrl => (req, res, next) => ctrl(req, res).catch(next)